//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class scoreboard_items
    {
        public int sbItem_id { get; set; }
        public string sbItem_playerName { get; set; }
        public Nullable<int> sbItem_score { get; set; }
        public Nullable<System.TimeSpan> sbItem_time { get; set; }
    }
}
